services:
  app.http.phalcon:
    decorates: app.http
    decoration_priority: 1000
    class: Vainyl\Symfony\Application\Decorator\SymfonyApplicationDecorator
    arguments: ['@app.http.phalcon.inner', '@psr.factory', '@symfony.factory', '@http_kernel']
  psr.factory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory
  symfony.factory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory