services:
  app.http.symfony:
    decorates: app.http
    decoration_priority: 1000
    class: Vainyl\Symfony\Application\Decorator\SymfonyApplicationDecorator
    arguments: ['@app.http.symfony.inner', '@psr.factory', '@symfony.factory', '@kernel']
  app.di: '@service_container'
  psr.factory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory
  symfony.factory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory
  bundle.storage:
    class: Vainyl\Symfony\Bundle\Storage\BundleStorage
    arguments: ['@map.prototype']
  event.listener.factory.symfony:
    class: Vainyl\Symfony\Event\SymfonyEventListenerFactory